name = "cloudflare-docker-proxy"
compatibility_date = "2024-09-02"
main = "src/index.js"
minify = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
MIRROR_DOMAIN = "mirror.xxx.cn"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.mirror.xxx.cn", custom_domain = true },
  { pattern = "gitlab.mirror.xxx.cn", custom_domain = true },
  { pattern = "gcr.mirror.xxx.cn", custom_domain = true },
  { pattern = "k8s.mirror.xxx.cn", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
MIRROR_DOMAIN = "mirror.xxx.cn"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = [
  { pattern = "docker-staging.mirror.xxx.cn", custom_domain = true }
]

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
MIRROR_DOMAIN = "mirror.xxx.cn"
